
spring:
  application:
    name: blog-api
  main:
    # bean 重新定义
    allow-bean-definition-overriding: true
  jackson:
    # json 字段中为空的不返回前端，不知什么原因无效
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: Admin@#$123
# 发送邮箱配置
  mail:
    host: smtp.163.com
    username: npc2048@163.com
    password: 7654123geg
    default-encoding: UTF-8
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
  configuration:
    map-underscore-to-camel-case: true
    # 实体类驼峰转下划线
    use-actual-param-name: true
    cache-enabled: false
# cors 跨域通用配置
cors:
  methods:
    - GET
    - POST
    - OPTIONS
  headers:
    - "*"
# 七牛云配置
qiniu:
  access-key: MiQ2n4QaOO2CSzCPO7-p6FITpOwH92sAM8MpM77p
  secret-key: I9J7QQbfaRjPh593Dyhqy7ottiP-JhwHyUaQiSas
  bucket: npc2048-file-server
  access-domain: http://q6cmjst9i.bkt.clouddn.com
# 日志配置
logging:
  file:
    name: spring.log
    clean-history-on-start: true
